CONFIG_SYS_MMCSD_FS_BOOT_PARTITION=y
CONFIG_BOOTCOMMAND="mmc dev ${mmcdev}; if mmc rescan; then if run loadbootscript; then run bootscript; else if run loadimage; then run mmcboot; else run netboot; fi; fi; else booti ${loadaddr} - ${fdt_addr}; fi"
CONFIG_BOARD_EARLY_INIT_F=y
CONFIG_IMX_CONFIG="arch/arm/mach-imx/imx8m/imximage.cfg"
CONFIG_SYS_FSL_ESDHC_ADDR=0
CONFIG_BOOTM_VXWORKS=y
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_SYS_LOAD_ADDR=$(CONFIG_LOADADDR)
CONFIG_SYS_FSL_MAX_NUM_OF_SEC=y
CONFIG_SYS_INIT_RAM_ADDR=0x40000000
CONFIG_SYS_HELP_CMD_WIDTH=10
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=1024
CONFIG_SYS_SPL_MALLOC_SIZE=0x80000
CONFIG_SYS_MONITOR_LEN="(512 * 1024)"
CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR=0x300
CONFIG_BOOTM_LINUX=y
CONFIG_BOARD_LATE_INIT=y
CONFIG_MII=y
CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_USE_SECTOR=y
CONFIG_SYS_FSL_SEC_ADDR="(CAAM_IPS_BASE_ADDR + CONFIG_SYS_FSL_SEC_OFFSET)"
CONFIG_CMD_FUSE=y
CONFIG_OF_SYSTEM_SETUP=y
CONFIG_SPL_LIBCOMMON_SUPPORT=y
CONFIG_PHY_GIGE=y
CONFIG_ENV_OFFSET="(64 * SZ_64K)"
CONFIG_MXC_OCOTP=y
CONFIG_ENV_OVERWRITE=y
CONFIG_ENV_SIZE=0x1000
CONFIG_CMD_PING=y
CONFIG_SPL_BUILD=y
CONFIG_SYS_MALLOC_LEN="((CONFIG_ENV_SIZE + (2 * 1024)) * 1024)"
CONFIG_SYS_MMC_ENV_DEV=y
CONFIG_SYS_I2C_SPEED=100000
CONFIG_IMX_BOOTAUX=y
CONFIG_MXC_UART=y
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_BOOTM_PLAN9=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_SPL_TEXT_BASE=0x7E1000
CONFIG_SYS_FSL_JR0_ADDR="(CONFIG_SYS_FSL_SEC_ADDR + CONFIG_SYS_FSL_JR0_OFFSET)"
CONFIG_POWER_I2C=y
CONFIG_SYS_MAXARGS=64
CONFIG_REMAKE_ELF=y
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)"
CONFIG_MXC_GPIO=y
CONFIG_BOARDDIR="board/freescale/imx8mq_evk"
CONFIG_POWER=y
CONFIG_POWER_PFUZE100_I2C_ADDR=0x08
CONFIG_SPL_STACK=0x187FF0
CONFIG_SYS_MAX_FLASH_SECT=512
CONFIG_PHYLIB=y
CONFIG_SPL_ABORT_ON_RAW_IMAGE=y
CONFIG_MFG_ENV_SETTINGS="CONFIG_MFG_ENV_SETTINGS_DEFAULT "initrd_addr=0x438000000initrd_high=0xffffffffffffffff0emmc_dev=00sd_dev=10""
CONFIG_SPL_I2C_SUPPORT=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_ZLIB=y
CONFIG_LOADADDR=0x40480000
CONFIG_ETHPRIME="FEC"
CONFIG_FSL_USDHC=y
CONFIG_SYS_MMC_IMG_LOAD_PART=y
CONFIG_SYS_FSL_SEC_OFFSET="(0)"
CONFIG_GZIP=y
CONFIG_SYS_INIT_RAM_SIZE=0x80000
CONFIG_FEC_MXC_PHYADDR=0x4
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_SPL_LIBGENERIC_SUPPORT=y
CONFIG_SYS_DCACHE_OFF=y
CONFIG_SPL_MMC_SUPPORT=y
CONFIG_SYS_SDRAM_BASE=0x40000000
CONFIG_PHY_ATHEROS=y
CONFIG_CMD_DHCP=y
CONFIG_SYS_PROMPT_HUSH_PS2="> "
CONFIG_SYS_FSL_USDHC_NUM=2
CONFIG_SYS_INIT_SP_OFFSET="(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_SYS_SPL_MALLOC_START=0x42200000
CONFIG_SYS_I2C_MXC_I2C2=y
CONFIG_SPL_WATCHDOG_SUPPORT=y
CONFIG_SYS_I2C=y
CONFIG_SPL_DRIVERS_MISC_SUPPORT=y
CONFIG_SPL_BSS_MAX_SIZE=0x2000
CONFIG_SPL_BSS_START_ADDR=0x00180000
CONFIG_SPL_PAD_TO=$(CONFIG_SPL_MAX_SIZE)
CONFIG_EXTRA_ENV_SETTINGS="CONFIG_MFG_ENV_SETTINGS JAILHOUSE_ENV "script=boot.scr0image=Image0console=ttymxc0,115200 earlycon=ec_imx6q,0x30860000,1152000fdt_addr=0x430000000fdt_high=0xffffffffffffffff0boot_fdt=try0fdt_file=myb-fsl-imx8mq-evk.dtb0initrd_addr=0x438000000initrd_high=0xffffffffffffffff0mmcdev=__stringify(CONFIG_SYS_MMC_ENV_DEV)"0mmcpart=" __stringify(CONFIG_SYS_MMC_IMG_LOAD_PART) "0mmcroot=" CONFIG_MMCROOT " rootwait rw0mmcautodetect=yes0mmcargs=setenv bootargs ${jh_clk} console=${console} root=${mmcroot}0 loadbootscript=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${script};0bootscript=echo Running bootscript from mmc ...; source0loadimage=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image}0loadfdt=fatload mmc ${mmcdev}:${mmcpart} ${fdt_addr} ${fdt_file}0mmcboot=echo Booting from mmc ...; run mmcargs; if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if run loadfdt; then booti ${loadaddr} - ${fdt_addr}; else echo WARN: Cannot load the DT; fi; else echo wait for boot; fi;0netargs=setenv bootargs ${jh_clk} console=${console} root=/dev/nfs ip=dhcp nfsroot=${serverip}:${nfsroot},v3,tcp0netboot=echo Booting from net ...; run netargs;  if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; ${get_cmd} ${loadaddr} ${image}; if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if ${get_cmd} ${fdt_addr} ${fdt_file}; then booti ${loadaddr} - ${fdt_addr}; else echo WARN: Cannot load the DT; fi; else booti; fi;0"
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)"
CONFIG_FSL_ESDHC=y
CONFIG_SPL_GPIO_SUPPORT=y
CONFIG_POWER_PFUZE100=y
CONFIG_SUPPORT_EMMC_BOOT=y
CONFIG_MXC_UART_BASE="UART1_BASE_ADDR"
CONFIG_SYS_SUPPORT_64BIT_DATA=y
CONFIG_SYS_SPL_PTE_RAM_BASE=0x41580000
CONFIG_FEC_MXC=y
CONFIG_USBD_HS=y
CONFIG_USB_MAX_CONTROLLER_COUNT=2
CONFIG_SPL_MAX_SIZE="(148 * 1024)"
CONFIG_SYS_MEMTEST_END="(CONFIG_SYS_MEMTEST_START + (PHYS_SDRAM_SIZE >> 1))"
CONFIG_SYS_PROMPT="u-boot=> "
CONFIG_MMCROOT="/dev/mmcblk1p2"
CONFIG_SYS_MEMTEST_START="PHYS_SDRAM"
CONFIG_LMB=y
CONFIG_SYS_ICACHE_OFF=y
CONFIG_FEC_XCV_TYPE="RGMII"
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_SERIAL_TAG=y
CONFIG_ENV_VARS_UBOOT_RUNTIME_CONFIG=y
CONFIG_SYS_I2C_MXC_I2C1=y
CONFIG_SYS_I2C_MXC_I2C3=y
CONFIG_MFG_ENV_SETTINGS_DEFAULT="mfgtool_args=setenv bootargs console=${console},${baudrate} rdinit=/linuxrc clk_ignore_unused 0kboot="MFG_BOOT_CMD"0bootcmd_mfg=run mfgtool_args;if iminfo ${initrd_addr}; then if test ${tee} = yes; then bootm ${tee_addr} ${initrd_addr} ${fdt_addr}; else " MFG_BOOT_CMD "${loadaddr} ${initrd_addr} ${fdt_addr}; fi; else " FASTBOOT_CMD "fi;0"
CONFIG_SYS_FSL_JR0_OFFSET="(0x1000)"
CONFIG_CMD_MII=y
CONFIG_CMD_MMC=y
CONFIG_SPL_POWER_SUPPORT=y
CONFIG_MALLOC_F_ADDR=0x182000
